"""
НЕФК — AJAX переклад UA ↔ EN (повна версія v3)
GET /api/translate/?lang=en|uk  → {lang, pairs: [[from, to], ...]}
Словник відсортований від довших фраз до коротших.
"""
from django.http import JsonResponse

UK_TO_EN = [
    # ══ NAVBAR / BRAND ══════════════════════════════════════════
    ("НЕФК Суспільство",                         "NEFC Society"),
    ("Стрічка",                                  "Feed"),
    ("Друзі",                                    "Friends"),
    ("Групи",                                    "Groups"),
    ("Повідомлення",                             "Messages"),
    ("Чат",                                      "Chat"),
    ("Сповіщення",                               "Notifications"),
    ("🔍 Пошук...",                              "🔍 Search..."),
    ("Пошук...",                                 "Search..."),
    ("Мій профіль",                              "My Profile"),
    ("Редагувати профіль",                       "Edit Profile"),
    ("Редагування профілю",                      "Edit Profile"),
    ("Редагувати",                               "Edit"),
    ("Налаштування сповіщень",                   "Notification Settings"),
    ("Налаштування",                             "Settings"),
    ("Адмін-панель",                             "Admin Panel"),
    ("Вийти",                                    "Log Out"),
    ("Увійти",                                   "Sign In"),
    ("Приєднатись",                              "Join Us"),

    # ══ ГОЛОВНА СТОРІНКА ════════════════════════════════════════
    ("Нововолинськ · вул. Шахтарська, 16 · Волинська обл.",
     "Novovolynsk · 16 Shakhtarska St. · Volyn Oblast"),
    ("Офіційна соціальна платформа студентів і викладачів Нovovolynsk Electromechanical Vocational College.",
     "Official social platform for students and teachers of the Novovolynsk Electromechanical Vocational College."),
    ("Офіційна соціальна платформа студентів і викладачів Нововолинського електромеханічного фахового коледжу.",
     "Official social platform for students and teachers of the Novovolynsk Electromechanical Vocational College."),
    ("Нификовий коледж у серці Волині",          "Leading college in the heart of Volyn"),
    ("Провідний технічний коледж Волинської області. Сучасна база, досвідчені викладачі, реальна практика.",
     "Leading technical college of Volyn Oblast. Modern facilities, experienced teachers, real practice."),
    ("НЕФК засновано у 1961 році. За понад 60 років підготовлено понад 10 000 фахівців.",
     "NEFC was founded in 1961. Over 60 years, 10,000+ specialists have graduated."),
    ("Суспільство",                              "Society"),
    ("Зареєструватись",                          "Sign Up"),
    ("рік заснування",                           "founded"),
    ("років досвіду",                            "years of experience"),
    ("спеціальності",                            "specialties"),
    ("випускників",                              "graduates"),
    ("студентів",                                "students"),
    ("викладачів",                               "teachers"),
    ("роки навчання",                            "years of study"),

    # Про коледж
    ("📍 Наш коледж",                            "📍 Our College"),
    ("Про коледж",                               "About College"),
    ("🎓 Освіта",                                "🎓 Education"),
    ("Спеціальності",                            "Specialties"),
    ("Чотири сучасні напрями підготовки. Держзамовлення, практика, диплом державного зразка.",
     "Four modern programs. State funding, internships, state-recognized diploma."),
    ("Комп'ютерна інженерія",                    "Computer Engineering"),
    ("Програмування Python/C++, системне адміністрування, мережева інфраструктура, кібербезпека.",
     "Python/C++ programming, system administration, network infrastructure, cybersecurity."),
    ("Електрична інженерія",                     "Electrical Engineering"),
    ("Електромонтаж, промислова автоматизація, ПЛК Siemens/Mitsubishi, SCADA-системи.",
     "Electrical installation, industrial automation, Siemens/Mitsubishi PLCs, SCADA systems."),
    ("Торгівля",                                 "Trade & Commerce"),
    ("Бізнес-аналітика, менеджмент, маркетинг, торговельна діяльність, 1С Підприємство.",
     "Business analytics, management, marketing, commercial activity, 1C Enterprise."),
    ("Прикладна механіка",                       "Applied Mechanics"),
    ("Металообробка, верстати з ЧПК, CAD/CAM проектування, роботизовані комплекси.",
     "Metal machining, CNC machines, CAD/CAM design, robotic complexes."),

    # Досягнення
    ("🏆 Досягнення",                            "🏆 Achievements"),
    ("Чим пишається НЕФК",                       "NEFC is proud of"),
    ("Переможці всеукраїнських олімпіад",         "National Olympiad Winners"),
    ("Студенти НЕФК щороку перемагають на олімпіадах з комп'ютерних дисциплін, електроніки та механіки.",
     "NEFC students win competitions in computer science, electronics and mechanics every year."),
    ("60%+ викладачів вищої категорії",          "60%+ Top-Category Teachers"),
    ("Педагогічний склад — лауреати конкурсів «Педагог року». Кандидати наук і доценти.",
     "Faculty — laureates of 'Teacher of the Year'. Candidates of sciences and docents."),
    ("Працевлаштування 85%+",                    "85%+ Employment Rate"),
    ("Більшість випускників отримують роботу ще під час навчання або одразу після диплому.",
     "Most graduates get jobs during or immediately after their studies."),
    ("Партнери — провідні компанії",             "Partners — Leading Companies"),
    ("IT-компанії, промислові підприємства Волині та всієї України. Реальна практика.",
     "IT companies, industrial enterprises of Volyn and Ukraine. Real internships."),

    # Календар
    ("📅 Календар",                              "📅 Calendar"),
    ("Важливі події",                            "Key Events"),
    ("1 вересня",                                "September 1"),
    ("🎒 День знань",                            "🎒 Knowledge Day"),
    ("Урочиста лінійка, зустріч першокурсників, святковий концерт.",
     "Ceremonial lineup, welcoming freshmen, festive concert."),
    ("Жовтень",                                  "October"),
    ("🚪 День відкритих дверей",                 "🚪 Open House Day"),
    ("Для абітурієнтів та батьків. Екскурсії, зустрічі з викладачами.",
     "For applicants and parents. Tours, meetings with faculty."),
    ("17 листопада",                             "November 17"),
    ("🎓 День студента",                         "🎓 Student Day"),
    ("КВК, творчі конкурси, дискотека. Найбільше свято студентів!",
     "Comedy club, creative contests, disco. The biggest student holiday!"),
    ("Квітень",                                  "April"),
    ("🔬 Науково-практична конференція",          "🔬 Science Conference"),
    ("Студентські дослідження, захист проектів, запрошені лектори.",
     "Student research, project presentations, invited industry speakers."),
    ("Червень",                                  "June"),
    ("🎉 Випускний вечір",                       "🎉 Graduation Night"),
    ("Урочисте вручення дипломів, прощальний концерт та банкет.",
     "Ceremonial diploma award, farewell concert and banquet."),

    # Вступ
    ("📋 Абітурієнту",                           "📋 Applicants"),
    ("Як вступити до НЕФК",                      "How to Apply to NEFC"),
    ("Без ЗНО / NMT, без вступних іспитів — тільки атестат. Чотири кроки до диплому.",
     "No entrance exams — just your certificate. Four steps to your diploma."),
    ("Крок 1",                                   "Step 1"),
    ("Документи",                                "Documents"),
    ("Атестат · паспорт · фото 3×4 · медична довідка 086-У · ідентифікаційний код",
     "Certificate · passport · 3×4 photo · medical form 086-U"),
    ("Крок 2",                                   "Step 2"),
    ("Конкурс",                                  "Competition"),
    ("Відбір за середнім балом атестата. Є місця держзамовлення!",
     "Selection by GPA. State-funded places available!"),
    ("Крок 3",                                   "Step 3"),
    ("Договір",                                  "Agreement"),
    ("Укладаємо договір. Денна та заочна форми навчання.",
     "Sign a study agreement. Full-time and part-time forms."),
    ("Крок 4",                                   "Step 4"),
    ("Навчання",                                 "Studies"),
    ("2–3 роки. Диплом молодшого бакалавра державного зразка.",
     "2–3 years. State-recognized junior bachelor diploma."),
    ("Детальніше на nemk.com.ua",               "More at nemk.com.ua"),
    ("Детальніше на офіційному сайті",           "More on official website"),

    # Контакти
    ("📞 Контакти",                              "📞 Contacts"),
    ("Зв'яжіться з нами",                        "Get in Touch"),
    ("НЕФК — Контакти",                          "NEFC — Contacts"),
    ("НЕФК — Контактна інформація",              "NEFC — Contact Information"),
    ("Адреса",                                   "Address"),
    ("вул. Шахтарська, 16\nм. Нававолинськ, Волинська обл., 45400",
     "16 Shakhtarska St.\nNovovolynsk, Volyn Oblast, 45400"),
    ("вул. Шахтарська, 16, м. Нававолинськ, Волинська обл.",
     "16 Shakhtarska St., Novovolynsk, Volyn Oblast"),
    ("вул. Шахтарська, 16, Нававолинськ, Волинська обл., 45400",
     "16 Shakhtarska St., Novovolynsk, Volyn Oblast, 45400"),
    ("вул. Шахтарська, 16, Нававолинськ",        "16 Shakhtarska St., Novovolynsk"),
    ("вул. Шахтарська, 16, Нановолинськ",        "16 Shakhtarska St., Novovolynsk"),
    ("вул. Шахтарська, 16, Нававолинськ",        "16 Shakhtarska St., Novovolynsk"),
    ("м. Нanovolynsk, вул. Шахтарська, 16",      "16 Shakhtarska St., Novovolynsk"),
    ("Телефон",                                  "Phone"),
    ("приймальна",                               "reception"),
    ("Графік роботи",                            "Working Hours"),
    ("Пн–Пт: 08:00 – 17:00",                    "Mon–Fri: 08:00 – 17:00"),
    ("Пн–Пт: 08:00–17:00",                      "Mon–Fri: 08:00–17:00"),
    ("Обід: 12:00–13:00 · Сб–Нд: вихідний",     "Lunch: 12:00–13:00 · Sat–Sun: closed"),
    ("Офіційний сайт",                           "Official Website"),
    ("Ми в соцмережах",                          "Follow Us"),
    ("Соцмережі",                                "Social Media"),

    # CTA
    ("🚀 Платформа",                             "🚀 Platform"),
    ("Стань частиною",                           "Join the"),
    ("Спілкуйся з однокурсниками, ділись конспектами, дізнавайся про події першим. Реєстрація безкоштовна.",
     "Connect with classmates, share notes, be the first to know. Registration is free."),
    ("Живий чат",                                "Live Chat"),
    ("WebSocket, групові чати, медіафайли",      "WebSocket, group chats, media files"),
    ("Знаходь однокурсників і викладачів",       "Find classmates and teachers"),
    ("За спеціальностями та інтересами",         "By specialty and interests"),
    ("Відповіді про НЕФК 24/7, жарти 😄",        "NEFC answers 24/7, jokes 😄"),
    ("AI-Асистент",                              "AI Assistant"),
    ("Вже в НЕФК Суспільстві",                   "Already in NEFC Society"),
    ("👥 Спільнота",                             "👥 Community"),

    # ══ СТРІЧКА (FEED) ══════════════════════════════════════════
    ("Що у тебе нового? Поділись з НЕМК спільнотою ✨",
     "What's on your mind? Share with NEFC community ✨"),
    ("Що у тебе нового? Поділись з НЕФК спільнотою ✨",
     "What's on your mind? Share with NEFC community ✨"),
    ("Опублікувати",                             "Publish"),
    ("😊 Загальне",                              "😊 General"),
    ("📚 Навчання",                              "📚 Study"),
    ("⚽ Спорт",                                "⚽ Sport"),
    ("🎉 Подія",                                 "🎉 Event"),
    ("🤔 Питання",                               "🤔 Question"),
    ("📢 Оголошення",                            "📢 Announcement"),
    ("Перетягни фото сюди",                      "Drag photo here"),
    ("Текст публікації",                         "Post text"),
    ("Тип публікації",                           "Post type"),
    ("😊 Статус",                                "😊 Status"),
    ("📸 Фото",                                  "📸 Photo"),
    ("🎥 Відео",                                 "🎥 Video"),
    ("🔗 Посилання",                             "🔗 Link"),
    ("🌐 Всі",                                   "🌐 All"),
    ("🎉 Події",                                 "🎉 Events"),
    ("📢 Оголошення",                            "📢 Announcements"),
    ("Стрічка порожня",                          "Feed is empty"),
    ("Додай друзів або підпишись на людей, щоб бачити їхні пости",
     "Add friends or follow people to see their posts"),
    ("🔍 Знайти людей",                          "🔍 Find people"),
    ("Поширено від",                             "Reposted from"),
    ("Відкрити",                                 "Open"),
    ("Скопіювати посилання",                     "Copy link"),
    ("Видалити публікацію?",                     "Delete post?"),
    ("Видалити",                                 "Delete"),
    ("Напиши коментар...",                       "Write a comment..."),
    ("🔁 Поширити",                              "🔁 Share"),
    ("Поширити",                                 "Share"),
    ("коментарів",                               "comments"),
    ("коментар",                                 "comment"),
    ("вподобань",                                "likes"),
    ("🌐 Всі",                                   "🌐 All"),
    ("🔥 Популярні теми",                        "🔥 Trending"),
    ("✨ Можливо знаєш",                         "✨ People you may know"),
    ("🌟 Можливо знаєш",                         "🌟 People you may know"),
    ("+ Читати",                                 "+ Follow"),
    ("Онлайн зараз",                             "Online Now"),
    ("Мої друзі",                                "My Friends"),
    ("нових запит",                              "new request"),
    ("Знайти людей",                             "Find People"),

    # Сайдбар
    ("🏠 Стрічка",                               "🏠 Feed"),
    ("👥 Друзі",                                 "👥 Friends"),
    ("📁 Групи",                                 "📁 Groups"),
    ("💬 Повідомлення",                          "💬 Messages"),
    ("🔔 Сповіщення",                            "🔔 Notifications"),
    ("🔍 Пошук",                                 "🔍 Search"),

    # ══ ПРОФІЛЬ ═════════════════════════════════════════════════
    ("публікацій",                               "posts"),
    ("Публікацій",                               "Posts"),
    ("Публікації",                               "Posts"),
    ("Публікацій ще немає.",                     "No posts yet."),
    ("підписників",                              "followers"),
    ("підписок",                                 "following"),
    ("Немає друзів.",                            "No friends yet."),
    ("Всі друзі",                                "All Friends"),
    ("Адмін",                                    "Admin"),
    ("Додати в друзі",                           "Add Friend"),
    ("Видалити з друзів",                        "Remove Friend"),
    ("Запит надіслано",                          "Request Sent"),
    ("Підписатись",                              "Follow"),
    ("Відписатись",                              "Unfollow"),

    # ══ ДРУЗІ ═══════════════════════════════════════════════════
    ("Запити у друзі",                           "Friend Requests"),
    ("У вас поки немає друзів.",                 "You have no friends yet."),
    ("нових запитів",                            "new requests"),

    # ══ ГРУПИ ═══════════════════════════════════════════════════
    ("Групи та спільноти",                       "Groups & Communities"),
    ("Нова група",                               "New Group"),
    ("Мої групи",                                "My Groups"),
    ("Всі спільноти",                            "All Communities"),
    ("учасників",                                "members"),
    ("Приватна",                                 "Private"),
    ("Поки немає груп.",                         "No groups yet."),
    ("Нова спільнота",                           "New Community"),
    ("Написати",                                 "Write Post"),
    ("Приєднатись",                              "Join"),
    ("Про групу",                                "About Group"),
    ("Учасники",                                 "Members"),
    ("Публікацій ще немає. Будь першим!",        "No posts yet. Be the first!"),

    # ══ СПОВІЩЕННЯ ══════════════════════════════════════════════
    ("Поки тихо",                                "All quiet"),
    ("Сповіщень немає. Заходь пізніше!",         "No notifications. Check back later!"),
    ("Обери, про що хочеш отримувати сповіщення.",
     "Choose what notifications you want to receive."),
    ("Зберегти налаштування",                    "Save Settings"),
    ("вподобав вашу публікацію",                 "liked your post"),
    ("прокоментував вашу публікацію",            "commented on your post"),
    ("поширив вашу публікацію",                  "shared your post"),
    ("тому",                                     "ago"),

    # ══ ЧАТ ═════════════════════════════════════════════════════
    ("Немає розмов.",                            "No conversations."),
    ("Оберіть розмову або почніть нову",         "Select a conversation or start a new one"),
    ("Початок розмови. Привітайся! 👋",          "Start of conversation. Say hi! 👋"),
    ("Груповий чат",                             "Group Chat"),
    ("Новий груповий чат",                       "New Group Chat"),
    ("Назва чату",                               "Chat Name"),
    ("Наприклад: Група ТП-21",                   "E.g.: Group CS-21"),
    ("Додати учасників (з друзів)",              "Add participants (from friends)"),
    ("Немає друзів для додавання.",              "No friends to add."),
    ("Написати повідомлення…",                   "Type a message…"),
    ("Груповий",                                 "Group"),

    # ══ ДЕТАЛІ ПОСТА ════════════════════════════════════════════
    ("Деталі публікації",                        "Post Details"),
    ("Коментарі",                                "Comments"),
    ("Поки немає коментарів. Будь першим!",      "No comments yet. Be the first!"),

    # ══ АВТОРИЗАЦІЯ ═════════════════════════════════════════════
    ("Вітаємо назад",                            "Welcome back"),
    ("Увійди в свій акаунт НЕФК",               "Sign in to your NEFC account"),
    ("Логін",                                    "Username"),
    ("Пароль",                                   "Password"),
    ("Ще немає акаунту?",                        "Don't have an account?"),
    ("Зареєструватись →",                        "Sign Up →"),
    ("Вже є акаунт?",                            "Already have an account?"),
    ("Увійти →",                                 "Sign In →"),
    ("Приєднуйся до НЕФК",                       "Join NEFC"),
    ("або",                                      "or"),
    ("Зберегти",                                 "Save"),
    ("Скасувати",                                "Cancel"),

    # ══ ПОШУК ═══════════════════════════════════════════════════
    ("Результати пошуку",                        "Search Results"),
    ("За запитом:",                              "For query:"),
    ("знайдено",                                 "found"),
    ("користувачів",                             "users"),
    ("Нікого не знайдено",                       "Nobody found"),
    ("Введи ім'я або нікнейм для пошуку",        "Enter a name or username to search"),

    # ══ ФУТЕР ═══════════════════════════════════════════════════
    ("Офіційна соціальна мережа студентів і викладачів Нawawolynsk Electromechanical Vocational College.",
     "Official social network of students and teachers of the Nowowolynsk EMF College."),
    ("Офіційна соціальна мережа студентів і викладачів Нowowolynsk Electromechanical Vocational College.",
     "Official social network of students and teachers of the Nowowolynsk EMF College."),
    ("Офіційна соціальна мережа студентів і викладачів Нawawolynsk електромеханічного фахового коледжу.",
     "Official social network of students and teachers of the Nowowolynsk EMF College."),
    ("вул. Шахтарська, 16, Нославолинськ",        "16 Shakhtarska St., Nowowolynsk"),
    ("Меню",                                     "Menu"),
    ("Контакти",                                 "Contacts"),
    ("Головна",                                  "Home"),
    ("Тема",                                     "Theme"),
    ("☀️ Світла",                               "☀️ Light"),
    ("🌙 Темна",                                 "🌙 Dark"),
    ("© 2024 НЕФК Суспільство. Всі права захищено.",
     "© 2024 NEFC Society. All rights reserved."),

    # ══ AI CHATBOT ══════════════════════════════════════════════
    ("НЕФК Асистент",                            "NEFC Assistant"),
    ("НЕФК-Асистент",                            "NEFC Assistant"),
    ("Онлайн 24/7 · Знає все про НЕФК",         "Online 24/7 · Knows everything about NEFC"),
    ("Запитай що завгодно...",                   "Ask me anything..."),
    ("НЕФК Суспільство · Rule-based AI",         "NEFC Society · Rule-based AI"),
    ("📍 Адреса",                                "📍 Address"),
    ("🎓 Спеціальності",                         "🎓 Specialties"),
    ("📋 Вступ",                                 "📋 Apply"),
    ("📅 Розклад",                               "📅 Schedule"),
    ("🏠 Гуртожиток",                            "🏠 Dorm"),
    ("💰 Стипендія",                             "💰 Scholarship"),
    ("😄 Жарт",                                  "😄 Joke"),
    ("💪 Мотивація",                             "💪 Motivation"),
    ("⚽ Спорт",                                 "⚽ Sport"),
    ("🤔 Яку обрати?",                           "🤔 Which to choose?"),
    ("📚 Бібліотека",                            "📚 Library"),
    ("🎭 Події",                                 "🎭 Events"),

    # ══ ЗАГАЛЬНЕ ════════════════════════════════════════════════
    ("Назад",                                    "Back"),
    ("Онлайн",                                   "Online"),
    ("Всі",                                      "All"),
    ("НЕФК",                                     "NEFC"),
]

# Автогенерація EN→UK
EN_TO_UK = [(en, uk) for uk, en in UK_TO_EN if uk != en]


def translate_view(request):
    lang = request.GET.get('lang', 'uk')
    if lang not in ('en', 'uk'):
        lang = 'uk'
    pairs = UK_TO_EN if lang == 'en' else EN_TO_UK
    # Сортуємо від довгих до коротких
    pairs_sorted = sorted(pairs, key=lambda p: -len(p[0]))
    return JsonResponse({'lang': lang, 'pairs': pairs_sorted})
